// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjd1u56S42yisxaPCwVuZuwywAahf-o28',
    appId: '1:262905385515:web:efbdb971a9c3d64382906e',
    messagingSenderId: '262905385515',
    projectId: 'taskweaver-front',
    authDomain: 'taskweaver-front.firebaseapp.com',
    storageBucket: 'taskweaver-front.appspot.com',
    measurementId: 'G-LBZ5B7SYRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdIglvI3X2q5M8EYYf3XrmHZ7Io1BBWw',
    appId: '1:262905385515:android:9c05f77cbce0af6382906e',
    messagingSenderId: '262905385515',
    projectId: 'taskweaver-front',
    storageBucket: 'taskweaver-front.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE2udvbIGJThJ471ZPCeZLy1HF1izRiTg',
    appId: '1:262905385515:ios:96fed2fce8fb555a82906e',
    messagingSenderId: '262905385515',
    projectId: 'taskweaver-front',
    storageBucket: 'taskweaver-front.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE2udvbIGJThJ471ZPCeZLy1HF1izRiTg',
    appId: '1:262905385515:ios:96fed2fce8fb555a82906e',
    messagingSenderId: '262905385515',
    projectId: 'taskweaver-front',
    storageBucket: 'taskweaver-front.appspot.com',
    iosBundleId: 'com.example.front',
  );
}
